name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, production]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  RUSTFLAGS: "-C link-arg=-s"

jobs:
  check:
    name: Quick Check
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-check"

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Run cargo check
        run: cargo check --all-features --locked
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Check formatting
        run: cargo fmt -- --check

  test:
    name: Test
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13]  # Apple Silicon and Intel
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Pkl
        run: |
          PKL_VERSION="0.28.2"
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # macOS-latest is Apple Silicon
            curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-macos-aarch64
          else
            # macOS-13 is Intel
            curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-macos-amd64
          fi
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          pkl --version

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ matrix.os }}"

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --all-features --locked
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Run clippy
        run: cargo clippy -- -D warnings
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

  build:
    name: Build
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-13
            target: x86_64-apple-darwin
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Pkl
        run: |
          PKL_VERSION="0.28.2"
          if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
            curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-macos-aarch64
          else
            curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-macos-amd64
          fi
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          pkl --version

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ matrix.target }}"

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 16

      - name: Verify binary
        run: |
          file target/${{ matrix.target }}/release/karabiner-pkl
          target/${{ matrix.target }}/release/karabiner-pkl --version