name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, production]

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13]  # Apple Silicon and Intel
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Pkl
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # macOS-latest is Apple Silicon
            curl -L -o pkl https://github.com/apple/pkl/releases/latest/download/pkl-macos-aarch64
          else
            # macOS-13 is Intel
            curl -L -o pkl https://github.com/apple/pkl/releases/latest/download/pkl-macos-amd64
          fi
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          pkl --version

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --all-features

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt -- --check

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-13
            target: x86_64-apple-darwin
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Pkl
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
            curl -L -o pkl https://github.com/apple/pkl/releases/latest/download/pkl-macos-aarch64
          else
            curl -L -o pkl https://github.com/apple/pkl/releases/latest/download/pkl-macos-amd64
          fi
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          pkl --version

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Verify binary
        run: |
          file target/${{ matrix.target }}/release/karabiner-pkl
          target/${{ matrix.target }}/release/karabiner-pkl --version