name: Test Suite

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  RUSTFLAGS: "-C link-arg=-s"

jobs:
  check:
    name: Quick Check
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-check"

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Run cargo check
        run: cargo check --all-features --locked
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Run clippy
        run: cargo clippy -- -D warnings
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Check formatting
        run: cargo fmt -- --check

  nextest:
    name: Nextest
    needs: check
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Pkl
        run: |
          PKL_VERSION="0.28.2"
          # Detect architecture and install appropriate Pkl binary
          if [[ $(uname -m) == "arm64" ]]; then
            curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-macos-aarch64
          else
            curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-macos-amd64
          fi
          chmod +x pkl
          sudo mv pkl /usr/local/bin/
          pkl --version

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-nextest"

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Run tests with nextest
        run: cargo nextest run --all-features --locked
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Generate test report
        if: always()
        run: cargo nextest run --all-features --locked --profile ci
        continue-on-error: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"